攻击潜能:
    攻击中: 3
    单攻击中: 5
    攻击大: 8
    队长中: 4
    队长大: 8

攻击:
    小: [0.2, 1]
    中: [0.3, 2]
    大: [0.5, 3]
    特大: [0.8, 4]
    上限: [1, false]

潜能倍率:
    方向中: 0.1
    方向大: 0.15
    解析小: 0.1
    解析中: 0.15

必杀基础倍率: 
    小: 1.2
    中: 1.5
    大: 1.7
    特大: 2
    极大: 2.3
    超特大: 2.5
    技能小: 0.8
    技能中: 1
    技能大: 1.2
    

上升幅度:
    无: 0
    中: 0.05
    大: 0.1
    非常大: 0.15

其他倍率:
    无: 0
    中: 0.2
    大: 0.4
    非常大: 0.6

必杀威力: 
    小: [0.35, 1]
    中: [0.5, 2]
    大: [0.75, 3]
    上限: [1.5, false]

必杀附加攻击: 
    中: 4
    大: 6
    特大: 8
    极大: 8
    超特大: 10
    技能小: 2
    技能中: 4
    技能大: 6

防御:
    小: [0.4, 1]
    中: [0.6, 2]
    大: [0.8, 3]
    上限: [1, true]

暴伤:
    小: [0.25, 1]
    中: [0.4, 2]
    大: [0.65, 3]
    上限: [1, true]

暴击防御: 
    小: [0.25, 1]
    中: [0.35, 2]
    上限: [1, true]

颜色耐性: 
    小: [0.15, 1]
    中: [0.25, 2]
    大: [0.4, 3]
    上限: [0.55, false]

必杀耐性: 
    小: [0.25, 1]
    中: [0.35, 2]
    大: [0.5, 3]
    上限: [0.5, false]

颜色威力:
    小: [0.15, 1]
    中: [0.25, 2]

潜能SP:
    SP小: 0.150001
    单SP小: 0.200001
    
SP获得:
    小: 0.250001
    中: 0.500001
    大: 0.750001
    特大: 1

SP:
    中: 5
    大: 10

攻击SP:
    1: [1, 5]
    2: [1, 3.5]
    3: [1, 2.5]



